[package]
name = "solver-wasm"
version = "0.1.0"
authors = ["pikumist <174439048+pikumist@users.noreply.github.com>"]
description = "A sample project with wasm-pack"
license = "MIT/Apache-2.0"
repository = "https://github.com/pikumist/puyomist/packages/solver-wasm"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
approx = "0.5.1"
num-traits = "0.2"
num-derive = "0.4"